services:
  - type: web
    name: live-staff-mvp
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_FILE
        value: /opt/render/project/data/data.sqlite
    disk:
      name: live-staff-data
      mountPath: /opt/render/project/data
      sizeGB: 1
